<?php

echo $title;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>

<br>
<br>
<form action="/user/logined" method="post">
    Login:   <input type="text" name="name" value=""><br>
Password:  <input type="text" name="password" value=""><br>
<!--    email:  <input type="text" name="email" value=""><br>-->
    <input type="submit" value="Authorize">
</form>
</body>
</html>

