<?php


namespace App\Controller;

use Base\Controller;
use Base\View;

class Index extends Controller
{
    public $login;

    public function indexAction()
    {

        echo "HUY";
    }

    public function setView(View $view)
    {
        return parent::setView($view); // TODO: Change the autogenerated stub
    }



}